CREATE OR REPLACE FUNCTION epoch_to_timestamp(epoch INTEGER)
RETURNS TIMESTAMP AS $$
DECLARE
    FILECOIN_GENESIS_UNIX_EPOCH CONSTANT INTEGER := 1598306400;
BEGIN
    -- Calculate and return the UNIX timestamp
    RETURN TO_TIMESTAMP(epoch * 30 + FILECOIN_GENESIS_UNIX_EPOCH);
END;
$$ LANGUAGE plpgsql;
