CREATE TYPE PAYLOAD_RETRIEVABILITY_STATE AS ENUM ('PAYLOAD_CID_NOT_QUERIED_YET', 'PAYLOAD_CID_UNRESOLVED', 'PAYLOAD_CID_RESOLVED','PAYLOAD_CID_TERMINALLY_UNRETRIEVABLE');
ALTER TABLE active_deals
ADD COLUMN payload_retrievability_state PAYLOAD_RETRIEVABILITY_STATE DEFAULT 'PAYLOAD_CID_NOT_QUERIED_YET',
ADD COLUMN last_payload_retrieval_attempt TIMESTAMPTZ;